### PR TITLE
Upgrade mqtt dependency

### PR DESCRIPTION
**Pull request by bradfol**

### CODE REVIEW

**Comment by rjhilgefort** [comment]
image

Looks like one of `mqtt` deps is using non-ES5 keywords (`class`). As it stands we're still supporting node `0.10` through `0.12`. Since node `0.12` is now out of LTS, it's possible we may be able to drop support.

@spacetc62 thoughts?

**Comment by bradfol** [comment]
@rjhilgefort While `mqtt` 2.4.0 was building on those versions of Node, according to their docs they removed support for Node 0.12 and earlier at 2.0.0:

> v2.0.0 removes support for node v0.8, v0.10 and v0.12
https://github.com/mqttjs/MQTT.js#important-notes-for-existing-users

**Comment by bradfol** [comment]
I have created a PR to remove those versions if the maintainers decide to do so. This PR depends on #15 to pass.

**Comment by spacetc62** [comment]
superseded by https://github.com/Losant/losant-mqtt-js/pull/16 so just closing this one

**Pull request closed without merging**
